### ISSUE TITLE
Error in migration engine:  Called `Option::unwrap()` on a `None` value

### ISSUE THREAD

**Issue by robabby** [prisma/migrate#233]
Hello!

I am working on upgrading a project from pirsma1 to prisma2.  I just upgraded my local prisma to 2.0.0-preview018, and am getting the error in the title of this post after running `prisma2 dev`.

Here's a paste of my terminal output:
```
➜  api git:(prism-nexus-upgrade) ✗ prisma2 dev

   Watching for changes in prisma/schema.prisma
   Last changed at 11/24/2019 3:34:01 PM


   Migrations
   ─────────────────────────────────────────────────────────────────────────────────────────────────────                     ✓ Database successfully migrated
   To save changes into a migration file, run prisma2 lift save


   Generators

   Watching for changes in prisma/schema.prisma
   Last changed at 11/24/2019 3:34:01 PM

   Migrations
   ─────────────────────────────────────────────────────────────────────────────────────────────────────                     ✓ Database successfully migrated
   To save changes into a migration file, run prisma2 lift save

   Watching for changes in prisma/schema.prisma
   Last changed at 11/24/2019 3:34:01 PM

   Migrations
   ─────────────────────────────────────────────────────────────────────────────────────────────────────                     ✓ Database successfully migrated
   To save changes into a migration file, run prisma2 lift save

   Watching for changes in prisma/schema.prisma
   Last changed at 11/24/2019 3:34:01 PM

   Migrations
   ─────────────────────────────────────────────────────────────────────────────────────────────────────                     ✓ Database successfully migrated
   To save changes into a migration file, run prisma2 lift save

Error

Error: Error in migration engine.
Reason: [src/libcore/option.rs:378:21] called `Option::unwrap()` on a `None` value

Please create an issue in the lift repo with
your `schema.prisma` and the prisma2 command you tried to use 🙏:
https://github.com/prisma/lift/issues/new

    at ChildProcess.<anonymous> (/home/rob/.nvm/versions/node/v12.13.1/lib/node_modules/prisma2/build/index.js:173939:35)       at ChildProcess.emit (events.js:210:5)
    at ChildProcess.EventEmitter.emit (domain.js:475:20)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
```

And here is a paste of my `shema.prisma` file:
```
generator photon {
  provider = "photonjs"
}

datasource db {
  provider = "postgresql"
  url      = "postgresql://postgres@localhost:5432/prisma?schema=prisma2"
}

model User {
  id Int @id
  createdAt DateTime @default(now())
  updatedAt DateTime @updatedAt
  avatarUrl String?
  credits Int? @default(0)
  discordAccessToken String?
  discordRefreshToken String?
  email String @unique
  followers Follow[] @relation(name: "Followers", references: id)
  follows Follow[] @relation(name: "Follows", references: id)
  friends User[]
  gamertag String?
  headerImgUrl String?
  isSherpa Boolean @default(false)
  isVerified Boolean @default(false)
  listings Listing[] @relation(name: "UserListings")
  password String
  primaryGame Game?
  primaryPlatform Platform?
  region String?
  timezone String?
  toDelete Boolean @default(false)
  username String @unique

  sherpa Sherpa? @relation(references: id)
  description String?
  upvotes Int @default(0)
  downvotes Int @default(0)
  services Service[]
}

model Sherpa {
  id Int @id
  createdAt DateTime @default(now())
  updatedAt DateTime @updatedAt
  description String?
  upvotes Int @default(0)
  downvotes Int @default(0)
  services Service[]
}

model Listing {
  id Int @id
  availableSlots Int @default(0)
  bounty Int? @default(0)
  createdAt DateTime @default(now())
  updatedAt DateTime @updatedAt
  dateCreated DateTime // TODO temporary field, delete when going live
  description String?
  eventDateTime DateTime
  game Game
  hasBounty Boolean @default(false)
  hasSherpa Boolean @default(false)
  isActive Boolean @default(true)
  isCompleted Boolean @default(false)
  isDeleted Boolean @default(false)
  listingType String
  owner User @relation(name: "UserListings")
  platform Platform
  players User[]
  sherpa Sherpa?
  slug String @unique
  tags Tag[]
  title String
}

model Follow {
  id Int @id
  createdAt DateTime @default(now())
  source User @relation(name: "Followers", references: id)
  target User @relation(name: "Follows", references: id)
}

model Service {
  id Int @id
  createdAt DateTime @default(now())
  description String
  game Game @relation(references: id)
  price Int
  sherpas User[] @relation(references: id)
  slug String @unique
  title String
  updatedAt DateTime @updatedAt
}

model Platform {
  id Int @id
  createdAt DateTime @default(now())
  updatedAt DateTime @updatedAt
  abbreviation String
  name String @unique
  logoPath String
  logoWhitePath String
  games Game[]
  slug String @unique
}

model Game {
  id Int @id
  createdAt DateTime @default(now())
  updatedAt DateTime @updatedAt
  name String @unique
  coverImgPath String
  headerImgPath String
  platforms Platform[]
  listings Listing[]
  services Service[]
  sherpas User[]
  slug String @unique
}

model Tag {
  id Int @id
  createdAt DateTime @default(now())
  updatedAt DateTime @updatedAt
  listings Listing[]
  value String @unique
}

model Token {
  id Int @id
  userId Int
  token String @unique
  createdAt DateTime @default(now())
}
```

I wouldn't be surprised if the error is due to mistakes in my schema file, but I am not seeing any errors in VS Code so 🤷‍♂

**Comment by artemzakharov** [comment]
Also seeing this, but with a schema that worked fine with previous versions of prisma 2. Coincidentally I'm also using Postgres, so that may have something to do with it.

**Comment by pantharshit00** [comment]
I am unable to reproduce this with `prisma2@2.0.0-preview018.1, binary version: bb7e89676c242c7fa4355fd09aa65ad2739c73cf`

![image](https://user-images.githubusercontent.com/22195362/70451218-f71fe500-1aca-11ea-946d-3984896115dd.png)

![image](https://user-images.githubusercontent.com/22195362/70451227-fe46f300-1aca-11ea-945c-005324e8cfd0.png)


Can you please make sure you are on that same version and try this again? Also, maybe try this with a fresh database. If you are upgrading from an older version of prisma 2 there are some breaking changes.

**Comment by robabby** [comment]
I updated to `prisma2@alpha` yesterday and was no longer hitting this error.

**Comment by artemzakharov** [comment]
I am also no longer hitting this error after upgrading, but that may be a false positive - the lift engine doesn't appear to be recognizing when it needs to update the DB _at all_ anymore, and simply returns "All migrations are already applied" no matter what. Can't really test to see if this is an issue with a vanilla database because my schema is so large that Prisma crashes if it tries to deploy the whole thing in one go... going to wait for the next preview release and see what happens, I guess.

**Comment by pantharshit00** [comment]
We fixed that bug in alpha recently as per this commit:
https://github.com/prisma/lift/pull/243 and #242 

Can you please try it on alpha one time.

**Comment by janpio** [comment]
> Can't really test to see if this is an issue with a vanilla database because my schema is so large that Prisma crashes if it tries to deploy the whole thing in one go... going to wait for the next preview release and see what happens, I guess.

Did you already report this in its own issue @artemzakharov and send @pantharshit00 your schema so we can reproduce this? We would love to be able to understand and fix this.

**Comment by artemzakharov** [comment]
Just tried again in the alpha branch, the `lift up` bug went away but the original bug is still there:
![image](https://user-images.githubusercontent.com/25446299/70652323-a665d480-1c0f-11ea-8ad5-565eb6c2cd08.png)

I _was_ able to get it to go through by deleting the data in all of the tables except `_Migration`, though - I think the real culprit may actually be somewhere in the change detection mechanism, because one of the other things I've noticed is that trying to deploy an update while still having some data in the DB creates an absolute onslaught of change detection warnings for completely unrelated tables and properties:

![image](https://user-images.githubusercontent.com/25446299/70657815-d4501680-1c19-11ea-91aa-d65f12461b68.png)

None of these properties have anything to do with the actual change.

@janpio Nevermind, I tried it again, and it actually deployed from zero successfully as long as I completely emptied the database ahead of time - the error I was remembering is actually related to it being unable to drop existing tables due to other objects depending on them, or something of the sort. False alarm.

**Comment by janpio** [comment]
False alarms are the best alarms :) Thanks for the update - @pantharshit00 will take over here again.

**Comment by pantharshit00** [comment]
@artemzakharov Are you still able to reproduce with preview019?

**Comment by artemzakharov** [comment]
Not sure if it's the same error under the hood, but when I try to deploy with `preview019` (after dropping the `_Migrations` table in accordance with the documentation for the release) I still get the same wall of `you are about to alter the column ... the data in that column will be lost` statements for pretty much every model/property in my DB, and the attempt to deploy terminates with:
```
Oops, an unexpected error occured!
Error in migration engine.
```
I submitted an error report, though it didn't give me an issue number to reference.

**Comment by artemzakharov** [comment]
I tried again after emptying the entire database, and just like before, the migration is suddenly able to go through, so it seems like it may still be the same error, or at least something related to it. Note that this is with **no changes to the schema** - I'm simply dropping the `_Migration` table on the target database, deleting the `migrations` folder in my project, and doing the usual save/up commands.

**Comment by tvvignesh** [comment]
@pantharshit00 Facing the same error on my end with latest alpha (2.0.0-alpha.648 and migrate 0.3.385)

Of all the databases I migrated, only one of them has the problem. Have deleted the migrations table from the db and also removed all the old generated migrations in source. Table does have data. Any way to migrate without clearing the data? On dev env I can clear if needed but I will apply the same migration in prod where I don't prefer to clear the data.

![Screenshot from 2020-01-24 23-40-59](https://user-images.githubusercontent.com/1165845/73092916-82cac500-3f03-11ea-924d-4685036405df.png)

**Comment by pantharshit00** [comment]
I am going to close this issue now as it is getting a bit cluttered. Please open a new issue if you facing any error.

> When errors like this occur in the future, is there any way to migrate without clearing the data? On dev env I can clear if needed but I will apply the same migration in prod where I don't prefer to clear the data or have some fallback mechanism in place. Thanks.

Right now you might be hitting a breaking change so that is why you need to clear your database sometimes. The goal is that we need to hit a level of stability that would not cause our tool to crash this like this. Then there will be no need to clear the data. If migrate crashes after we announce it as production ready(it is in preview right now), you would report us the error and we would fix it then you would use it in production.
