### ISSUE TITLE
Unexpected error occured when running migrate up in latest alpha.

### ISSUE THREAD

**Issue by AlexanderProd** [prisma/migrate#322]
When running `npx prisma2 migrate up --experimental` in the latest alpha `2.0.0-alpha.618` there's an unexpected error. 

```
Checking the datasource for potential data loss...
ERROR  Oops, an unexpected error occured!
```
Unfortunately there aren't more details to the error. 
I've tried it a couple times and checked if there's a problem with my db or connection. 

OS: macOS
Prisma2 version: 2.0.0-alpha.618 (using alpha because of prisma/prisma2#1419 )
DB: MySQL
Report id: 1354

Schema:
```
datasource mysql {
  url      = "mysql://******:*****@******/*****"
  provider = "mysql"
}

generator client {
  provider = "prisma-client-js"
}

model User {
  id        String   @id @default(cuid())
  createdAt DateTime @default(now())
  email     String   @unique
  name      String?
  phone     String?
  role      Role     @default(USER)
  posts     Post[]
}

model Post {
  id         String     @id @default(cuid())
  createdAt  DateTime   @default(now())
  updatedAt  DateTime   @updatedAt
  author     User
  title      String
  categories Category[]
  published  Boolean    @default(false)
}

model Category {
  id    String  @id @default(cuid())
  name  String 
}

enum Role {
  USER
  ADMIN
}
```

those are the changes that would've been applied: 
<img width="441" alt="image" src="https://user-images.githubusercontent.com/3080903/72978715-3f733800-3dd7-11ea-9a5a-d7501c177af7.png">

**Comment by pantharshit00** [comment]
I am unable to reproduce this Mysql 5.7 and prisma2 version `prisma2@2.0.0-preview020.2, binary version: 0150d2c09b7ddee6b866a924dea38ba157ad4980` which contains the fix for the other issue that you have mentioned.

I will install MariaDB and try to reproduce this again with that.

**Comment by tvvignesh** [comment]
I get this error when running migrate up on alpine but not on ubuntu. Not sure why OS plays a role here. Using prisma2 `2.0.0-alpha.636` `@prisma/migrate: 0.3.374`

I had deleted the migrations table from the database since yesterday's breaking change. All migrations got applied successfully when I run it via Ubuntu, but if the same command is running in alpine it throws this error.

![Screenshot from 2020-01-24 10-15-54](https://user-images.githubusercontent.com/1165845/73045912-e28a8700-3e95-11ea-839c-bb48b6122c10.png)

Not sure why I am the magnet of all errors or maybe I am doing something wrong :cry:

**Comment by tomhoule** [comment]
Alpha 626 shouldn't exhibit this bug anymore - are you sure it happens with latest alpha?

**Comment by tomhoule** [comment]
@AlexanderProd we fixed a few issues since yesterday, it would be super helpful if you could try again with the latest `prisma2@alpha` :)

**Comment by AlexanderProd** [comment]
@tomhoule just tried `npx prisma2 migrate up --experimental` and still getting the unexpected error. I'm using `prisma2@2.0.0-alpha.636, binary version: 45dd3493ff2fd09b5a8cdf697de276e368f7ebee`

also submitted new error report with id 1389.

**Comment by AlexanderProd** [comment]
I also just tried `npx prisma2 migrate up --experimental` (the same schema and migration) against a completely empty DB and this time on a proper MySQL 5.7.29. 

This is what would've been done
<img width="716" alt="image" src="https://user-images.githubusercontent.com/3080903/73061111-afe28d80-3e99-11ea-8a0c-5b6827a8a9e2.png">
 
But I'm still getting the unexpected error unfortunately.

**Comment by tvvignesh** [comment]
> @tvvignesh Alpha 626 shouldn't exhibit this bug anymore - are you sure it happens with latest alpha?

Yup. It happens in the latest alpha, but interestingly, not in Ubuntu, only in alpine. I am not sure why. If I figure out, I will let you know.

**Comment by AlexanderProd** [comment]
I've created a new project without any legacy migrations from prior version and this time `migrate up` works fine.

**Comment by pantharshit00** [comment]
@tvvignesh Are you still facing this? Otherwise, we can close this

**Comment by tvvignesh** [comment]
> @tvvignesh Are you still facing this? Otherwise, we can close this

@pantharshit00 Since I had this error, I upgraded to latest version of prisma, changed lift to migrate and also cleaned up the database and local migrations and also stopped applying it everytime the server starts. After that, things are going smooth so far.

You can close this for now, if I face it again, will let you know. Thanks.
